# Generated by Django 4.1.3 on 2022-11-30 03:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "カテゴリ",
                "verbose_name_plural": "カテゴリ",
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="※入力必須項目", max_length=255, verbose_name="本のタイトル"
                    ),
                ),
                (
                    "author",
                    models.CharField(blank=True, max_length=30, verbose_name="本の著者名"),
                ),
                (
                    "publisher",
                    models.CharField(blank=True, max_length=30, verbose_name="本の出版社"),
                ),
                (
                    "buydate",
                    models.DateField(
                        blank=True,
                        default=datetime.datetime.now,
                        null=True,
                        verbose_name="購入日",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="※入力必須項目<br>※重複書籍の登録防止になります",
                        max_length=255,
                        unique=True,
                        verbose_name="本のURL（楽天ブックスのURLを入力ください）",
                    ),
                ),
                (
                    "rental",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="※要望あれば、自動インクリメント機能を実装します",
                        verbose_name="本の貸し出し回数（お手数ですが、貸し出し時に数値をインクリメントください）",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="※本を返却するときは、E-Mailを削除ください",
                        max_length=255,
                        verbose_name="本の貸出先E-Mail（本のレンタル時は、E-Mailを入力ください）",
                    ),
                ),
                (
                    "memo",
                    models.TextField(blank=True, max_length=255, verbose_name="メモ"),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=255, verbose_name="本のコメント（書評）"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="book.category",
                        verbose_name="カテゴリ",
                    ),
                ),
            ],
            options={
                "verbose_name": "本の登録",
                "verbose_name_plural": "本の登録",
                "db_table": "book",
            },
        ),
    ]
